server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # Configurations git repository URL
          uri: https://github.com/hasinduudara/agms-config-repo.git
          default-label: main